apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: felipexd3/gitopsfc
  newTag: aff69d928101bc346d4e4e61b3a831fae96d1c64
