#nome workflow
name: CD Gitops

#sempre que algum push ocorrer na main
on:
  push:
    branches: [main]

#tarefas a serem executadas
jobs:
  #tarefa de build
  build:
    name: Build
    #tarefa será executada no seguinte SO
    runs-on: ubuntu-latest

    #Passos a serem executados. Aceita uma lista
    steps:
    - name: Checkout code
      #Action do github que será executada (esta serve para fazer checkout)
      uses: actions/checkout@v2

    - name: Build and push image to Dockerhub
      #Action para buildar e pushar para o dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/gitopsfc
        #cria tag na imagem com hash do commit no git e como latest
        tags: ${{ github.sha }}, latest